### ISSUE TITLE
Partner Risk Rating search control doesn't allow removal of highest risk, experimental partners

### ISSUE THREAD

**Issue by pickettd** [nuclearspike/kivalensjs#1]
I really appreciate your work on Kivalens (both the old Silverlight version and the new, awesome React version).

I wanted to let you know that I think I found an issue in the search/filter by Risk Rating. It looks like Not Rated partners are being included in the search results even when the slider for the Partner Risk Rating search criteria setting is set with a value that doesn't include the min value (e.g. 4-max). I've attached screenshots of my settings and results also. I've seen experiment (not rated) partners Pana Pana and MicroLoan Foundation (MLF) Malawi show up even though my search settings should be for lower risk partners.

The search settings where I'm getting this result are:
Borrower:
Everything default/blank except the Repaid In field (I brought it down to min-3 or so)

Partner:
Region: blank
Social Performance: blank
Risk Rating: 4-max (or 4-4.5 still has the same result)
Delinq Rate: min-10
Default Rate: min-10
Everything else default (min-max)

Thanks again for all your work!
-David
![1-borrower-settings](https://cloud.githubusercontent.com/assets/410782/11165354/388cdc28-8ab0-11e5-9e71-5c03b850be8c.png)
![2-partner-settings](https://cloud.githubusercontent.com/assets/410782/11165355/388e52d8-8ab0-11e5-86f9-d19847fc1185.png)
![3-experimental-partner-rating-on-lens-and-kiva](https://cloud.githubusercontent.com/assets/410782/11165356/388f7a82-8ab0-11e5-9052-e05399fb5cb8.png)

**Comment by nuclearspike** [comment]
thanks for the report! confirmed, fixed and on prod
