### ISSUE TITLE
Error running `yarn start`

### ISSUE THREAD

**Issue by jfoo1984** [nuclearspike/kivalensjs#36]
When I try to run `yarn start`, I get this error

```
[13:23:29] Finished 'client' compilation after 4429 ms
[13:23:29] Launching server...
Error: ENOENT: no such file or directory, scandir '/tmp/batches'
    at Object.readdirSync (node:fs:1392:3)
    at Module../src/server.js (/Users/jfu/kivalens/src/server.js:71:1)
```

Looks like that directory is referenced here: https://github.com/nuclearspike/kivalens/blob/master/src/server.js#L72

Does it need to be manually created?

**Comment by jfoo1984** [comment]
This ticket should've been filed in https://github.com/nuclearspike/kivalens instead of this repo.  It was fixed in that repo in https://github.com/nuclearspike/kivalens/commit/a631d1cc0703cf6b7926ef5b84df8c473e525d93

**Comment by nuclearspike** [comment]
Yeah, the main thread starts to try to read the dir before the thread
creates it when the dir doesn't already exist. I'd caught and fixed that
the other night but hadn't committed it yet. I just did a commit with that
change. Are you on Mac/Linux or Windows?
